apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magicord-bot
  template:
    metadata:
      labels:
        app: magicord-bot
    spec:
      containers:
      - name: magicord-bot
        image: your_dockerhub_username/magicord-bot:latest
        ports:
        - containerPort: 3000
        env:
        - name: DISCORD_TOKEN
          value: "YOUR_DISCORD_BOT_TOKEN"
        - name: CLIENT_ID
          value: "YOUR_CLIENT_ID"
        - name: GUILD_ID
          value: "YOUR_GUILD_ID"
