apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-commands-job
spec:
  template:
    spec:
      containers:
      - name: deploy-commands
        image: magicord
        command: ["node", "deploy-commands.js"]
      restartPolicy: OnFailure
