#!/bin/bash
# Start Minikube (if not already running)
minikube start

# Set Docker environment to Minikube
eval $(minikube docker-env)


# Apply Kubernetes deployment and service (replace with your actual YAML file names)
kubectl apply -f deploy-commands-job.yaml
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml


# Get logs to monitor bot (optional)
kubectl logs -f $(kubectl get pods --selector=app=discord-bot -o jsonpath='{.items[0].metadata.name}')